version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
  redhat8:
    image: registry.access.redhat.com/ubi8/ubi:latest
    container_name: redhat8
